### ISSUE TITLE
Bundler can't resolve a JSON file in the project root directory with file name that starts with "."

### ISSUE THREAD

**Issue by matthamil** [facebook/metro-bundler#40]
## Bug Report

The bundler can't resolve JSON files in the root directory with a file name of `.foo.json`. It _can_ resolve JSON files with a name of `foo.json`.

### What is the current behavior?
When importing a JSON file from a JS file like so:

```js
import { thing } from './.thing.json'; // note the . at the beginning of the file name
export const bar = thing.foo;
```

The bundler will crash with the following:

```sh
Bundling `index.ios.js`  [development, non-minified, hmr disabled]  99.3% (297/298), failed.
Error: Expected root module to be relative to one of the project roots
    at toLocalPath (/Users/matthamil/workspace/reactnative/Ralli/node_modules/metro-bundler/src/node-haste/lib/toLocalPath.js:29:9)
    at ModuleCache.getModule (/Users/matthamil/workspace/reactnative/Ralli/node_modules/metro-bundler/src/node-haste/ModuleCache.js:93:20)
    at ModuleResolver._loadAsFile (/Users/matthamil/workspace/reactnative/Ralli/node_modules/metro-bundler/src/node-haste/DependencyGraph/ModuleResolution.js:416:48)
    at ModuleResolver._loadAsFileOrThrow (/Users/matthamil/workspace/reactnative/Ralli/node_modules/metro-bundler/src/node-haste/DependencyGraph/ModuleResolution.js:380:25)
    at tryResolveSync (/Users/matthamil/workspace/reactnative/Ralli/node_modules/metro-bundler/src/node-haste/DependencyGraph/ModuleResolution.js:233:10)
    at tryResolveSync (/Users/matthamil/workspace/reactnative/Ralli/node_modules/metro-bundler/src/node-haste/DependencyGraph/ModuleResolution.js:111:12)
    at ModuleResolver._resolveFileOrDir (/Users/matthamil/workspace/reactnative/Ralli/node_modules/metro-bundler/src/node-haste/DependencyGraph/ModuleResolution.js:231:12)
    at ModuleResolver.resolveNodeDependency (/Users/matthamil/workspace/reactnative/Ralli/node_modules/metro-bundler/src/node-haste/DependencyGraph/ModuleResolution.js:255:19)
    at ResolutionRequest.resolveDependency (/Users/matthamil/workspace/reactnative/Ralli/node_modules/metro-bundler/src/node-haste/DependencyGraph/ResolutionRequest.js:109:14)
    at dependencyNames.map.name (/Users/matthamil/workspace/reactnative/Ralli/node_modules/metro-bundler/src/node-haste/DependencyGraph/ResolutionRequest.js:118:10)
```

I think the bug is related to [this function](https://github.com/facebook/metro-bundler/blob/74e78ee43f73d0452dcce0db0887f055cf7abbee/packages/metro-bundler/src/node-haste/DependencyGraph/ResolutionRequest.js#L82). I could be wrong. That's where the error is being thrown in my stack trace.

### Steps to reproduce:

Create a new React Native project. In the root project directory, create a `.thing.json` file like so:

```json
{
  "thing": {
    "foo": "bar"
  }
}
```

Create a JS file also in the root directory, call it something like `MyConfig.js`.

Make `MyConfig.js` look like the following:

```js
import { thing } from './.thing.json'; // note the . at the beginning of the file name
export const bar = thing.foo;
```

In the `index.ios.js` file, add the following line to the top of the file:

`import { bar } from './MyConfig';`

and change the render method to look like:

```jsx
render() {
  return (
    <View>
      <Text>{bar}</Text>
    </View>
  );
}
```

Run `react-native start` and `react-native run-ios`.

### What is the expected behavior?

The JSON file should be imported without any problems. If you change the file name of the JSON file to `thing.json` _without_ the prepended `.` in the file name (and update the `import` statement in `MyConfig.js`), the import works fine.

### Environment:

| software         | version
| ---------------- | -------
| Metro Bundler |  0.9.2
| react-native     |  0.47.1
| node             | 8.2.1
| yarn      | 0.24.5

**Comment by cpojer** [comment]
Closing in favor of the PR.
