### ISSUE TITLE
Packager is broken on current RN master

### ISSUE THREAD

**Issue by janicduplessis** [facebook/metro-bundler#62]
The packager is currently crashing when generating a bundle on RN master. It seem to be caused by a difference in the version of jest-haste-map. Adding .default to [this require](https://github.com/facebook/metro-bundler/blob/master/packages/metro-bundler/src/node-haste/DependencyGraph/ResolutionRequest.js#L25) fixes the issue.

Error log from RN OSS CI:
```
error: bundling failed: TypeError: Right-hand side of 'instanceof' is not an object

    at ResolutionRequest._resolveHasteDependency (/Users/travis/build/facebook/react-native/node_modules/metro-bundler/src/node-haste/DependencyGraph/ResolutionRequest.js:124:17)

    at ModuleResolution.tryResolveSync (/Users/travis/build/facebook/react-native/node_modules/metro-bundler/src/node-haste/DependencyGraph/ResolutionRequest.js:103:18)

    at Object.tryResolveSync (/Users/travis/build/facebook/react-native/node_modules/metro-bundler/src/node-haste/DependencyGraph/ModuleResolution.js:113:12)

    at ResolutionRequest.resolveDependency (/Users/travis/build/facebook/react-native/node_modules/metro-bundler/src/node-haste/DependencyGraph/ResolutionRequest.js:102:39)

    at dependencyNames.map.name (/Users/travis/build/facebook/react-native/node_modules/metro-bundler/src/node-haste/DependencyGraph/ResolutionRequest.js:136:10)

    at Array.map (<anonymous>)

    at ResolutionRequest.resolveModuleDependencies (/Users/travis/build/facebook/react-native/node_modules/metro-bundler/src/node-haste/DependencyGraph/ResolutionRequest.js:135:42)

    at module.readFresh.then (/Users/travis/build/facebook/react-native/node_modules/metro-bundler/src/node-haste/DependencyGraph/ResolutionRequest.js:183:16)

    at <anonymous>

    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by jeanlauliac** [comment]
I'm perplexed, what could have changed that causes that to happen now. When I do `require('jest-haste-map/build/module_map')` in node.js REPL, I get directly the exports rather than a `default`.

I guess the proper fix is to use `require('jest-haste-map').ModuleMap.DuplicateHasteCandidatesError` instead of requiring something deep in the library. Will send the fix.

**Comment by janicduplessis** [comment]
Strange, maybe we are resolving to different versions? I have `21.1.0` which does `  }}exports.default = ModuleMap;`. I agree using `require('jest-haste-map')` is the proper fix.

**Comment by skevy** [comment]
I can confirm that this fix worked @jeanlauliac with RN master when I link in metro-bundler master...but we need to publish a new version of metro to make sure that a fresh clone of RN builds properly.

**Comment by maxhalty** [comment]
In the new version v0.21.1 this is happening to me again. I just used the previews version v0.20.3 and now everything is working fine.
