### ISSUE TITLE
budler failed: UnableToResolveError: Unable to resolve module `../../../../.cache/typescript/2.6/node_modules/@types/prop-types`

### ISSUE THREAD

**Issue by santhosh77h** [facebook/metro-bundler#95]
**Do you want to request a *feature* or report a *bug*?**
It's a bug from metro bundler i hope but not sure

**What is the current behavior?**
on react-native start it crashes on the run with the following error
` 

 could not resolve 
/home/payzello/.cache/typescript/2.6/node_modules/@types/prop-types' as a file nor as a folder
     at UnableToResolveError (/proj/path/node_modules/metro-bundler/src/node-haste/DependencyGraph/ModuleResolution.js:591:5)
     at ModuleResolver._loadAsFileOrDirOrThrow (/proj/path/node_modules/metro-bundler/src/node-haste/DependencyGraph/ModuleResolution.js:337:11)
     at ModuleResolver._resolveFileOrDir (/proj/path/node_modules/metro-bundler/src/node-haste/DependencyGraph/ModuleResolution.js:222:17).
     at ModuleResolver.resolveNodeDependency (/proj/path/node_modules/metro-bundler/src/node-haste/DependencyGraph/ModuleResolution.js:236:19)
     at ResolutionRequest.resolveDependency (/proj/pathnode_modules/metro-bundler/src/node-haste/DependencyGraph/ResolutionRequest.js:109:14)
     at dependencyNames.map.name (/proj/path/node_modules/metro-bundler/src/node-haste/DependencyGraph/ResolutionRequest.js:134:10)
     at Array.map (native)
     at ResolutionRequest.resolveModuleDependencies (/proj/path/node_modules/metro-bundler/src/node-haste/DependencyGraph/ResolutionRequest.js:133:42)
     at module.readFresh.then (/proj/path/node_modules/metro-bundler/src/node-haste/DependencyGraph/ResolutionRequest.js:181:16)
     at process._tickCallback (internal/process/next_tick.js:109:7)

`

**Environment**

Environment:
  OS: Linux 3.10
  Node: 6.11.0
  Yarn: 1.2.0
  npm: 3.10.10
  Watchman: 4.7.0
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  react: ^16.0.0 => 16.0.0
  react-native: ^0.50.4 => 0.50.4

**Comment by nikasvan** [comment]
How did you fix this? Before closing an issue please let us know about the answer, helps community!
